export const products = [
  {
    name: 'Ao Dai 0',
    picture: 'aodai0.jpg',
    description: [
      'Ao Dai. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Ao Dai 1',
    picture: 'aodai1.jpg',
    description: [
      'Ao Dai. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Ao Dai 2',
    picture: 'aodai2.jpg',
    description: [
      'Ao Dai. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'BlackWhite',
    picture: 'bw.jpg',
    description: [
      'BlackWhite. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Duck',
    picture: 'duck.jpg',
    description: [
      'Duck. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Cat',
    picture: 'cat.jpg',
    description: [
      'Cat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Lantern',
    picture: 'lantern.jpg',
    description: [
      'Lantern. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },
  {
    name: 'Road',
    picture: 'road.jpg',
    description: [
      'Road. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis convallis tellus id interdum velit. Sed id semper risus in hendrerit gravida rutrum quisque non. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Id aliquet risus feugiat in. Eu non diam phasellus vestibulum lorem sed. Nisi quis eleifend quam adipiscing vitae. Ut etiam sit amet nisl purus in mollis. Augue neque gravida in fermentum et sollicitudin. Nunc sed augue lacus viverra. Felis bibendum ut tristique et egestas.',
      'Lorem ipsum dolor sit amet consectetur adipiscing.Nulla aliquet enim tortor at auctor urna.At varius vel pharetra vel turpis nunc.Duis at tellus at urna condimentum mattis pellentesque.Vitae sapien pellentesque habitant morbi.Neque viverra justo nec ultrices dui sapien eget mi.Diam volutpat commodo sed egestas egestas fringilla.Adipiscing bibendum est ultricies integer quis auctor elit.Risus at ultrices mi tempus.Erat pellentesque adipiscing commodo elit at.Montes nascetur ridiculus mus mauris vitae.Ultrices gravida dictum fusce ut placerat.Integer feugiat scelerisque varius morbi.',
      'Sagittis orci a scelerisque purus semper eget.Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.Pretium viverra suspendisse potenti nullam ac tortor.Ut venenatis tellus in metus vulputate eu scelerisque felis.Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.Id volutpat lacus laoreet non curabitur gravida arcu ac tortor.Eu mi bibendum neque egestas.Suscipit adipiscing bibendum est ultricies integer quis auctor.Risus nullam eget felis eget nunc.Habitasse platea dictumst quisque sagittis.Quis risus sed vulputate odio ut enim blandit volutpat maecenas.At quis risus sed vulputate odio ut.Et netus et malesuada fames ac turpis.Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla.',
      'A pellentesque sit amet porttitor eget dolor.Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.Urna nunc id cursus metus aliquam eleifend mi in nulla.Arcu cursus vitae congue mauris rhoncus aenean vel elit.Mauris pharetra et ultrices neque.Magna ac placerat vestibulum lectus mauris ultrices eros.Ultrices in iaculis nunc sed augue lacus viverra vitae.Phasellus egestas tellus rutrum tellus.Facilisis sed odio morbi quis commodo odio.Lectus urna duis convallis convallis.Purus viverra accumsan in nisl nisi scelerisque.Leo a diam sollicitudin tempor id eu.Ipsum dolor sit amet consectetur adipiscing elit duis.Ullamcorper sit amet risus nullam.Sodales ut eu sem integer vitae justo eget.']
  },

];
